language: elixir
elixir:
  - 1.7.1
otp_release:
  - 20.0
  - 20.1
script: "MIX_ENV=test mix local.hex --force && MIX_ENV=test mix do deps.get, test && mix format --check-formatted && mix dialyzer --halt-exit-status"
